apiVersion: v1
kind: Service
metadata: 
  name: example
  namespace: muzeyyen
spec:
  selector:
    name: example
  ports: 
    - name: http
      protocol: TCP
      port: 7770
      targetPort: 5080


